/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness of the API and its database connection. */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matches, newest first, without their moves. */
        get: operations["list_matches"];
        put?: never;
        /** Puts single games between two verified bots into the queue, at least one of them the account's own (E98). At most 20 games a day per account; they start after the matches of admins. */
        post: operations["enqueue_own_matches"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        /** One match with all moves played so far. */
        get: operations["get_match"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}/pgn": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        /** The match as PGN, also while it runs (result * until it ends). */
        get: operations["get_match_pgn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All verified bots, ordered by name and version. */
        get: operations["list_bots"];
        put?: never;
        /** Uploads a bot as source files; the runner then verifies it (E91, E92). The same name as an own bot makes a new version of it, with a higher version number. */
        post: operations["upload_bot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bots/{bot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bot_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        /** One bot with the versions of its name. Verified, disabled and retired bots are public; the owner and admins also see the others, and they alone get the details with the verification report (E15, E95). */
        get: operations["get_bot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Changes the description of an own bot, or retires a verified one and makes it verified again (owner, E95, E96). A bot disabled by an admin stays disabled. */
        patch: operations["update_own_bot"];
        trace?: never;
    };
    "/bots/{bot_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bot_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        /** One file of an uploaded bot as a download (owner and admins, E97). Bots that are not public are not found for others. */
        get: operations["get_bot_file"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bots/{bot_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bot_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        /** All files of an uploaded bot as a ZIP file named Name-Version.zip, in a folder Name-Version (owner and admins, E97). */
        get: operations["get_bot_source"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Running and waiting matches in queue order with estimated start times (E20). */
        get: operations["get_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who is logged in; user is null for guests. */
        get: operations["get_session"];
        put?: never;
        /** Logs in and sets the session cookie. */
        post: operations["login"];
        /** Ends the session and clears the cookie; also fine without a session. */
        delete: operations["logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates an account from an invite and logs it in (E4, E83). */
        post: operations["redeem_invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/password-resets/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sets a new password with a reset link from an admin, ends all other sessions of the account and logs it in. */
        post: operations["redeem_password_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Changes the own password and ends all other sessions of the account. */
        put: operations["change_password"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/bots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The bots of the logged-in account in every status, newest first. */
        get: operations["list_own_bots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All accounts, ordered by name (admin). */
        get: operations["list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Changes role or active state of another account (admin); deactivation ends its sessions. */
        patch: operations["update_user"];
        trace?: never;
    };
    "/admin/users/{user_id}/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A one-time link that sets a new password, valid for 24 hours (admin, E83). An earlier unused link of the account stops working. */
        post: operations["create_password_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unused invites that have not expired, newest first (admin). */
        get: operations["list_invites"];
        put?: never;
        /** A new one-time invite (admin, E4). */
        post: operations["create_invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invites/{invite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invite_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Withdraws an open invite (admin). */
        delete: operations["revoke_invite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bots/{bot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bot_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Disables a verified or retired bot, or makes a disabled one verified again (admin, E93, E96); queued matches of a disabled bot are aborted when their turn comes. */
        patch: operations["update_bot"];
        trace?: never;
    };
    "/admin/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Puts single games between two verified bots into the queue (admin, E71, E85). */
        post: operations["enqueue_matches"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Pauses or resumes the queue (admin); a running match plays to its end. */
        patch: operations["update_queue"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Identifier of a document: 24 lowercase hexadecimal digits. */
        Id: string;
        /** Format: date-time */
        Timestamp: string;
        Error: {
            /** @enum {unknown} */
            code: "invalid_parameter" | "not_found" | "unavailable" | "internal" | "unauthenticated" | "forbidden" | "csrf_failed" | "invalid_credentials" | "invalid_token" | "username_taken" | "too_many_attempts" | "name_taken" | "upload_conflict" | "invalid_upload" | "too_large";
            /** @description English text for logs; not shown to users, except as the detail of invalid_upload. */
            message: string;
            /** @description The invalid parameter, for invalid_parameter. */
            field?: string;
            /** @description The file to blame, for invalid_upload. */
            path?: string;
        };
        Health: {
            /** @constant */
            status: "ok";
        };
        /**
         * @description aborted: discarded after infrastructure errors and not played again (match-runner.md).
         * @enum {unknown}
         */
        MatchStatus: "queued" | "running" | "finished" | "aborted";
        Result: components["schemas"]["result"];
        Termination: components["schemas"]["termination"];
        /** @description The conditions the match was played under, copied when it was created. */
        Discipline: {
            name: string;
            initial_time_ms: number;
            increment_ms: number;
            startup_ms: number;
            tolerance_ms: number;
            max_moves: number;
        };
        /** @description One side of a match. sdk and lang are filled once the bot reported ready. */
        Side: {
            /** @constant */
            kind: "bot";
            bot_id: components["schemas"]["Id"];
            name: string;
            sdk: string | null;
            lang: string | null;
            /** @description Version of the bot; null for matches queued before versions were kept (E95). */
            version: string | null;
        };
        /** @description The fields of MatchSummary, open for extension by Match. */
        MatchFields: {
            id: components["schemas"]["Id"];
            /** @constant */
            type: "single";
            status: components["schemas"]["MatchStatus"];
            white: components["schemas"]["Side"];
            black: components["schemas"]["Side"];
            discipline: components["schemas"]["Discipline"];
            /** @description null until the match ends. */
            result: components["schemas"]["result"] | null;
            /** @description null until the match ends. */
            termination: components["schemas"]["termination"] | null;
            ply_count: number;
            created_at: components["schemas"]["Timestamp"];
            started_at: components["schemas"]["Timestamp"] | null;
            finished_at: components["schemas"]["Timestamp"] | null;
        };
        MatchSummary: components["schemas"]["MatchFields"];
        Move: {
            /** @description 1 for White's first move. */
            ply: number;
            uci: string;
            san: string;
            /** @description Position after the move. */
            fen: string;
            /** @description Thinking time of this move. */
            spent_ms: number;
            /** @description The mover's remaining time after the move, increment included. */
            clock_ms: number;
            /** @description Search information the bot reported, public (E33). */
            info: components["schemas"]["info"] | null;
        };
        Match: {
            start_fen: string;
            moves: components["schemas"]["Move"][];
        } & components["schemas"]["MatchFields"];
        MatchPage: {
            items: components["schemas"]["MatchSummary"][];
            /** @description Matches matching the filter. */
            total: number;
        };
        /**
         * @description uploaded, analyzing, testing: in the verification; verified: plays; rejected: failed the verification; disabled: stopped by an admin; retired: withdrawn by its owner (verifikation.md, E96).
         * @enum {unknown}
         */
        BotStatus: "uploaded" | "analyzing" | "testing" | "verified" | "rejected" | "disabled" | "retired";
        /** @description 3 to 32 letters, digits, _ . or -, starting with a letter or digit; regardless of case the name of one owner's bots (E91). */
        BotName: string;
        /** @description X.Y.Z, each part 0 to 999 without leading zeros (E91). */
        BotVersion: string;
        /** @description The fields of Bot, open for extension by BotDetail. */
        BotFields: {
            id: components["schemas"]["Id"];
            name: string;
            version: string;
            /** @enum {unknown} */
            language: "python" | "cpp" | "java" | "csharp" | "javascript";
            status: components["schemas"]["BotStatus"];
            /** @description A reference bot shipped with the SDK (E68, E72). */
            builtin: boolean;
            /** @description Plain text by the owner, at most 500 characters; line breaks but no other control characters (E95). */
            description: string;
            created_at: components["schemas"]["Timestamp"];
        };
        Bot: components["schemas"]["BotFields"];
        BotDetail: {
            /** @description Only for the owner and admins; null for everyone else. */
            details: components["schemas"]["BotDetails"] | null;
            /** @description The versions of the name the viewer may see, this one included, newest first (E95). */
            versions: components["schemas"]["Bot"][];
        } & components["schemas"]["BotFields"];
        BotFile: {
            path: string;
            /**
             * @description data: a file for load_data in data/.
             * @enum {unknown}
             */
            kind: "source" | "data";
            /** @description Bytes. */
            size: number;
        };
        BotDetails: {
            /** @description Name of the owner; null for reference bots. */
            owner: string | null;
            /** @description The file the bot starts with; null for reference bots. */
            entry: string | null;
            files: components["schemas"]["BotFile"][];
            /** @description SDK version of the runtime that verified the bot. */
            sdk_version: string | null;
            runtime_version: string | null;
            verified_at: components["schemas"]["Timestamp"] | null;
            rejected_at: components["schemas"]["Timestamp"] | null;
            rejection: components["schemas"]["Rejection"] | null;
            /** @description null until the verification ends, and for reference bots. */
            report: components["schemas"]["VerificationReport"] | null;
        };
        /**
         * @description internal: the server could not verify the bot (E92).
         * @enum {unknown}
         */
        VerificationStageName: "analysis" | "tests" | "internal";
        Rejection: {
            stage: components["schemas"]["VerificationStageName"];
            /** @description English text from the runner. */
            reason: string;
        };
        /** @description A problem the static analysis found (statische-analyse.md). */
        Finding: {
            rule: string;
            file: string;
            line: number | null;
            /** @description English text from the analyzer. */
            message: string;
        };
        /** @description One Mindesttest: a game against the reference bot Random (verifikation.md). */
        TestGame: {
            name: string;
            /**
             * @description The colour of the bot.
             * @enum {unknown}
             */
            color: "white" | "black";
            result: components["schemas"]["result"];
            termination: components["schemas"]["termination"];
            detail: string;
            plies: number;
            passed: boolean;
            /** @description Why the test failed. */
            problem: string | null;
        };
        VerificationStage: {
            stage: components["schemas"]["VerificationStageName"];
            /** @enum {unknown} */
            status: "passed" | "failed";
            duration_ms: number;
            /** @description Why the stage failed. */
            problem: string | null;
            /** @description Stage analysis. */
            findings?: components["schemas"]["Finding"][];
            /** @description Stage analysis: there were more findings than listed. */
            truncated?: boolean;
            /** @description Stage tests, up to the first that failed. */
            tests?: components["schemas"]["TestGame"][];
        };
        VerificationReport: {
            /** @enum {unknown} */
            result: "passed" | "failed";
            /** @description The rules of the static analysis, e.g. python-1. */
            ruleset: string | null;
            /** @description Versions in the bots' runtime, e.g. python and sdk. */
            runtime: {
                [key: string]: string;
            };
            started_at: components["schemas"]["Timestamp"];
            finished_at: components["schemas"]["Timestamp"];
            stages: components["schemas"]["VerificationStage"][];
        };
        /** @description Paths are relative with /; .py files and data files directly in data/, at most 100 of each and 1 MiB each in all (verifikation.md). At most 20 uploads a day per account. */
        BotUpload: {
            name: components["schemas"]["BotName"];
            /** @description Higher than every earlier version of the name. */
            version: components["schemas"]["BotVersion"];
            /**
             * @description Only Python so far.
             * @constant
             */
            language: "python";
            /**
             * @description The file the bot starts with, in the top folder.
             * @default bot.py
             */
            entry: string;
            /**
             * @description Plain text by the owner, at most 500 characters; line breaks but no other control characters (E95).
             * @default
             */
            description: string;
            /** @description The path of each file, in the order of files. */
            paths: string[];
            files: string[];
        };
        BotUpdate: {
            /** @enum {unknown} */
            status: "verified" | "disabled";
        };
        OwnBotUpdate: {
            /** @description Plain text by the owner, at most 500 characters; line breaks but no other control characters (E95). */
            description?: string;
            /**
             * @description retired withdraws a verified bot, verified brings it back (E96).
             * @enum {unknown}
             */
            status?: "verified" | "retired";
        };
        BotList: {
            items: components["schemas"]["Bot"][];
        };
        QueueEntry: {
            match: components["schemas"]["MatchSummary"];
            /** @description 1 for the next match to start; 0 for running matches. */
            position: number;
            /** @description When the match should start; for running matches when it started. */
            estimated_start: components["schemas"]["Timestamp"];
            estimated_end: components["schemas"]["Timestamp"];
        };
        Queue: {
            /** @description No new matches start while the queue is paused. */
            paused: boolean;
            running: components["schemas"]["QueueEntry"][];
            /** @description In start order; at most 200 entries. */
            waiting: components["schemas"]["QueueEntry"][];
            waiting_total: number;
        };
        /** @description 3 to 32 letters, digits, _ . or -, starting with a letter or digit; unique regardless of case (E83). */
        Username: string;
        /** @description 10 to 128 characters (E84). */
        Password: string;
        /** @description The secret part of an invite or reset link, after the # (E83). */
        OneTimeToken: string;
        /**
         * @description coder: own bots; admin: everything (backend-api.md).
         * @enum {unknown}
         */
        Role: "coder" | "admin";
        CurrentUser: {
            id: components["schemas"]["Id"];
            username: string;
            role: components["schemas"]["Role"];
        };
        SessionState: {
            /** @description null for guests. */
            user: components["schemas"]["CurrentUser"] | null;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        RedeemInvite: {
            token: components["schemas"]["OneTimeToken"];
            username: components["schemas"]["Username"];
            password: components["schemas"]["Password"];
        };
        RedeemPasswordReset: {
            token: components["schemas"]["OneTimeToken"];
            password: components["schemas"]["Password"];
        };
        ChangePassword: {
            current_password: string;
            new_password: components["schemas"]["Password"];
        };
        User: {
            id: components["schemas"]["Id"];
            username: string;
            role: components["schemas"]["Role"];
            /** @description A deactivated account cannot log in. */
            active: boolean;
            created_at: components["schemas"]["Timestamp"];
            last_login_at: components["schemas"]["Timestamp"] | null;
        };
        UserList: {
            items: components["schemas"]["User"][];
        };
        /** @description At least one field; admins cannot change their own account this way. */
        UserUpdate: {
            role?: components["schemas"]["Role"];
            active?: boolean;
        };
        OneTimeLink: {
            /** @description The page of the SPA with the token after the #, so it stays out of server logs. */
            url: string;
            expires_at: components["schemas"]["Timestamp"];
        };
        Invite: {
            id: components["schemas"]["Id"];
            role: components["schemas"]["Role"];
            /** @description Name of the admin; null for invites from the command line. */
            created_by: string | null;
            created_at: components["schemas"]["Timestamp"];
            expires_at: components["schemas"]["Timestamp"];
        };
        InviteList: {
            items: components["schemas"]["Invite"][];
        };
        InviteRequest: {
            role: components["schemas"]["Role"];
            /**
             * @description How long the invite can be used.
             * @default 7
             */
            valid_days: number;
        };
        CreatedInvite: {
            invite: components["schemas"]["Invite"];
            /** @description The page of the SPA with the token after the #, so it stays out of server logs. */
            url: string;
        };
        /** @description The discipline is named after the time control in seconds, e.g. 180+2 or 20+0.5; bots get 10 s to start (E85). */
        EnqueueRequest: {
            white_bot_id: components["schemas"]["Id"];
            black_bot_id: components["schemas"]["Id"];
            initial_time_ms: number;
            /** @default 0 */
            increment_ms: number;
            /** @default 1 */
            games: number;
            /**
             * @description Swap colours after every game.
             * @default false
             */
            alternate: boolean;
            /**
             * @description Higher starts first; equal priorities in the order queued.
             * @default 100
             */
            priority: number;
            /**
             * @description Full moves until the game is drawn.
             * @default 500
             */
            max_moves: number;
            /** @description Start position; null or missing for the standard position. */
            start_fen?: string | null;
        };
        /** @description Like EnqueueRequest with tighter limits: from the standard position with the default move limit, at most 5 min + 5 s and 10 games (E98). */
        OwnMatchRequest: {
            white_bot_id: components["schemas"]["Id"];
            black_bot_id: components["schemas"]["Id"];
            initial_time_ms: number;
            /** @default 0 */
            increment_ms: number;
            /** @default 1 */
            games: number;
            /**
             * @description Swap colours after every game.
             * @default false
             */
            alternate: boolean;
        };
        EnqueuedMatches: {
            match_ids: components["schemas"]["Id"][];
        };
        QueueUpdate: {
            paused: boolean;
        };
        /**
         * @description PGN result; * if the game was aborted without rating.
         * @enum {unknown}
         */
        result: "1-0" | "0-1" | "1/2-1/2" | "*";
        /**
         * @description Machine-readable reason, the same codes as stored in the database.
         * @enum {unknown}
         */
        termination: "checkmate" | "resignation" | "timeout" | "illegal_move" | "protocol_violation" | "crash" | "memory_limit" | "startup_timeout" | "stalemate" | "threefold_repetition" | "fifty_move_rule" | "insufficient_material" | "timeout_insufficient_material" | "max_moves" | "aborted";
        /** @description Move in UCI notation, promotion piece in lower case. The null move 0000 is not allowed. */
        uci: string;
        /** @description Optional search information, shown publicly in the viewer (E33). Display only. */
        info: {
            depth?: number;
            seldepth?: number;
            /** @description Score in centipawns from the bot's point of view. */
            score_cp?: number;
            /** @description Mate in this many moves; negative if the bot gets mated. */
            score_mate?: number;
            nodes?: number;
            /** @description Principal variation, starting with the move played. */
            pv?: components["schemas"]["uci"][];
            text?: string;
        };
    };
    responses: {
        /** @description A parameter is invalid (code invalid_parameter). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such resource (code not_found). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The database is unreachable (code unavailable). */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No valid session (code unauthenticated). */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The X-SBM-CSRF header is missing (code csrf_failed) or the account may not do this (code forbidden). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unknown name, wrong password or deactivated account (code invalid_credentials); for routes that need a session also unauthenticated. */
        InvalidCredentials: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many attempts from this address or for this account; try again later (code too_many_attempts, E84). */
        TooManyAttempts: {
            headers: {
                /** @description Seconds until the next attempt may succeed. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A field is invalid (code invalid_parameter) or the link is unknown, used or expired (code invalid_token). */
        BadToken: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The name is in use, also in another case (code username_taken). */
        UsernameTaken: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A field is invalid (code invalid_parameter), or the files break the upload rules (code invalid_upload, with the file to blame in path, if there is one). */
        BadUpload: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The name belongs to a bot of another account or to a reference bot (code name_taken), or another upload of the name came first (code upload_conflict). */
        NameTaken: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request is larger than 3 MiB (code too_large). */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The session after the request. */
        Session: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SessionState"];
            };
        };
    };
    parameters: {
        /** @description Protection against cross-site requests: browsers send this header from other sites only after a CORS preflight, which the API never allows (E84). Without it the API answers 403 with code csrf_failed. */
        Csrf: "1";
        UserId: components["schemas"]["Id"];
        MatchId: components["schemas"]["Id"];
        /** @description Page size. */
        Limit: number;
        /** @description Number of items to skip. */
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API answers and reaches the database. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    list_matches: {
        parameters: {
            query?: {
                /** @description Only matches with this status. */
                status?: components["schemas"]["MatchStatus"];
                /** @description Only matches in which this bot plays either colour. */
                bot_id?: components["schemas"]["Id"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
                /** @description Number of items to skip. */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of matches. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchPage"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    enqueue_own_matches: {
        parameters: {
            query?: never;
            header: {
                /** @description Protection against cross-site requests: browsers send this header from other sites only after a CORS preflight, which the API never allows (E84). Without it the API answers 403 with code csrf_failed. */
                "X-SBM-CSRF": components["parameters"]["Csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnMatchRequest"];
            };
        };
        responses: {
            /** @description The new matches in the order they were queued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnqueuedMatches"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyAttempts"];
        };
    };
    get_match: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The match. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    get_match_pgn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One PGN game. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-chess-pgn": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    list_bots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The bots. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotList"];
                };
            };
        };
    };
    upload_bot: {
        parameters: {
            query?: never;
            header: {
                /** @description Protection against cross-site requests: browsers send this header from other sites only after a CORS preflight, which the API never allows (E84). Without it the API answers 403 with code csrf_failed. */
                "X-SBM-CSRF": components["parameters"]["Csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["BotUpload"];
            };
        };
        responses: {
            /** @description The new bot, waiting for its verification. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotDetail"];
                };
            };
            400: components["responses"]["BadUpload"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["NameTaken"];
            413: components["responses"]["TooLarge"];
            429: components["responses"]["TooManyAttempts"];
        };
    };
    get_bot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bot_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The bot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    update_own_bot: {
        parameters: {
            query?: never;
            header: {
                /** @description Protection against cross-site requests: browsers send this header from other sites only after a CORS preflight, which the API never allows (E84). Without it the API answers 403 with code csrf_failed. */
                "X-SBM-CSRF": components["parameters"]["Csrf"];
            };
            path: {
                bot_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnBotUpdate"];
            };
        };
        responses: {
            /** @description The changed bot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    get_bot_file: {
        parameters: {
            query: {
                /** @description The path as listed in the details. */
                path: string;
            };
            header?: never;
            path: {
                bot_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The bytes of the file as uploaded. */
            200: {
                headers: {
                    /** @description Always attachment, with the file name. */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    get_bot_source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bot_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ZIP file. */
            200: {
                headers: {
                    /** @description Always attachment, with the file name. */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": unknown;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    get_queue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The queue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Queue"];
                };
            };
        };
    };
    get_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Session"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header: {
                /** @description Protection against cross-site requests: browsers send this header from other sites only after a CORS preflight, which the API never allows (E84). Without it the API answers 403 with code csrf_failed. */
                "X-SBM-CSRF": components["parameters"]["Csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: components["responses"]["Session"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["InvalidCredentials"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyAttempts"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /** @description Protection against cross-site requests: browsers send this header from other sites only after a CORS preflight, which the API never allows (E84). Without it the API answers 403 with code csrf_failed. */
                "X-SBM-CSRF": components["parameters"]["Csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    redeem_invite: {
        parameters: {
            query?: never;
            header: {
                /** @description Protection against cross-site requests: browsers send this header from other sites only after a CORS preflight, which the API never allows (E84). Without it the API answers 403 with code csrf_failed. */
                "X-SBM-CSRF": components["parameters"]["Csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemInvite"];
            };
        };
        responses: {
            201: components["responses"]["Session"];
            400: components["responses"]["BadToken"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["UsernameTaken"];
            429: components["responses"]["TooManyAttempts"];
        };
    };
    redeem_password_reset: {
        parameters: {
            query?: never;
            header: {
                /** @description Protection against cross-site requests: browsers send this header from other sites only after a CORS preflight, which the API never allows (E84). Without it the API answers 403 with code csrf_failed. */
                "X-SBM-CSRF": components["parameters"]["Csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemPasswordReset"];
            };
        };
        responses: {
            200: components["responses"]["Session"];
            400: components["responses"]["BadToken"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyAttempts"];
        };
    };
    change_password: {
        parameters: {
            query?: never;
            header: {
                /** @description Protection against cross-site requests: browsers send this header from other sites only after a CORS preflight, which the API never allows (E84). Without it the API answers 403 with code csrf_failed. */
                "X-SBM-CSRF": components["parameters"]["Csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePassword"];
            };
        };
        responses: {
            /** @description The password is changed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["InvalidCredentials"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyAttempts"];
        };
    };
    list_own_bots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The bots. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The accounts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    update_user: {
        parameters: {
            query?: never;
            header: {
                /** @description Protection against cross-site requests: browsers send this header from other sites only after a CORS preflight, which the API never allows (E84). Without it the API answers 403 with code csrf_failed. */
                "X-SBM-CSRF": components["parameters"]["Csrf"];
            };
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description The changed account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    create_password_reset: {
        parameters: {
            query?: never;
            header: {
                /** @description Protection against cross-site requests: browsers send this header from other sites only after a CORS preflight, which the API never allows (E84). Without it the API answers 403 with code csrf_failed. */
                "X-SBM-CSRF": components["parameters"]["Csrf"];
            };
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The link; it is shown only this once. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OneTimeLink"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    list_invites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The open invites. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    create_invite: {
        parameters: {
            query?: never;
            header: {
                /** @description Protection against cross-site requests: browsers send this header from other sites only after a CORS preflight, which the API never allows (E84). Without it the API answers 403 with code csrf_failed. */
                "X-SBM-CSRF": components["parameters"]["Csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteRequest"];
            };
        };
        responses: {
            /** @description The invite with its link; the link is shown only this once. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedInvite"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    revoke_invite: {
        parameters: {
            query?: never;
            header: {
                /** @description Protection against cross-site requests: browsers send this header from other sites only after a CORS preflight, which the API never allows (E84). Without it the API answers 403 with code csrf_failed. */
                "X-SBM-CSRF": components["parameters"]["Csrf"];
            };
            path: {
                invite_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The invite no longer works. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    update_bot: {
        parameters: {
            query?: never;
            header: {
                /** @description Protection against cross-site requests: browsers send this header from other sites only after a CORS preflight, which the API never allows (E84). Without it the API answers 403 with code csrf_failed. */
                "X-SBM-CSRF": components["parameters"]["Csrf"];
            };
            path: {
                bot_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BotUpdate"];
            };
        };
        responses: {
            /** @description The changed bot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    enqueue_matches: {
        parameters: {
            query?: never;
            header: {
                /** @description Protection against cross-site requests: browsers send this header from other sites only after a CORS preflight, which the API never allows (E84). Without it the API answers 403 with code csrf_failed. */
                "X-SBM-CSRF": components["parameters"]["Csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnqueueRequest"];
            };
        };
        responses: {
            /** @description The new matches in the order they were queued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnqueuedMatches"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    update_queue: {
        parameters: {
            query?: never;
            header: {
                /** @description Protection against cross-site requests: browsers send this header from other sites only after a CORS preflight, which the API never allows (E84). Without it the API answers 403 with code csrf_failed. */
                "X-SBM-CSRF": components["parameters"]["Csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueueUpdate"];
            };
        };
        responses: {
            /** @description The queue settings now in force. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueUpdate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
}
