/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness of the API and its database connection. */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matches, newest first, without their moves. */
        get: operations["list_matches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        /** One match with all moves played so far. */
        get: operations["get_match"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}/pgn": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        /** The match as PGN, also while it runs (result * until it ends). */
        get: operations["get_match_pgn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All bots, ordered by name. */
        get: operations["list_bots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bots/{bot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bot_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        /** One bot. */
        get: operations["get_bot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Running and waiting matches in queue order with estimated start times (E20). */
        get: operations["get_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Identifier of a document: 24 lowercase hexadecimal digits. */
        Id: string;
        /** Format: date-time */
        Timestamp: string;
        Error: {
            /** @enum {unknown} */
            code: "invalid_parameter" | "not_found" | "unavailable" | "internal";
            /** @description English text for logs; not shown to users. */
            message: string;
            /** @description The invalid parameter, for invalid_parameter. */
            field?: string;
        };
        Health: {
            /** @constant */
            status: "ok";
        };
        /**
         * @description aborted: discarded after infrastructure errors and not played again (match-runner.md).
         * @enum {unknown}
         */
        MatchStatus: "queued" | "running" | "finished" | "aborted";
        Result: components["schemas"]["result"];
        Termination: components["schemas"]["termination"];
        /** @description The conditions the match was played under, copied when it was created. */
        Discipline: {
            name: string;
            initial_time_ms: number;
            increment_ms: number;
            startup_ms: number;
            tolerance_ms: number;
            max_moves: number;
        };
        /** @description One side of a match. sdk and lang are filled once the bot reported ready. */
        Side: {
            /** @constant */
            kind: "bot";
            bot_id: components["schemas"]["Id"];
            name: string;
            sdk: string | null;
            lang: string | null;
        };
        /** @description The fields of MatchSummary, open for extension by Match. */
        MatchFields: {
            id: components["schemas"]["Id"];
            /** @constant */
            type: "single";
            status: components["schemas"]["MatchStatus"];
            white: components["schemas"]["Side"];
            black: components["schemas"]["Side"];
            discipline: components["schemas"]["Discipline"];
            /** @description null until the match ends. */
            result: components["schemas"]["result"] | null;
            /** @description null until the match ends. */
            termination: components["schemas"]["termination"] | null;
            ply_count: number;
            created_at: components["schemas"]["Timestamp"];
            started_at: components["schemas"]["Timestamp"] | null;
            finished_at: components["schemas"]["Timestamp"] | null;
        };
        MatchSummary: components["schemas"]["MatchFields"];
        Move: {
            /** @description 1 for White's first move. */
            ply: number;
            uci: string;
            san: string;
            /** @description Position after the move. */
            fen: string;
            /** @description Thinking time of this move. */
            spent_ms: number;
            /** @description The mover's remaining time after the move, increment included. */
            clock_ms: number;
            /** @description Search information the bot reported, public (E33). */
            info: components["schemas"]["info"] | null;
        };
        Match: {
            start_fen: string;
            moves: components["schemas"]["Move"][];
        } & components["schemas"]["MatchFields"];
        MatchPage: {
            items: components["schemas"]["MatchSummary"][];
            /** @description Matches matching the filter. */
            total: number;
        };
        Bot: {
            id: components["schemas"]["Id"];
            name: string;
            /** @enum {unknown} */
            language: "python" | "cpp" | "java" | "csharp" | "javascript";
            /** @constant */
            status: "verified";
            /** @description A reference bot shipped with the SDK (E68, E72). */
            builtin: boolean;
            created_at: components["schemas"]["Timestamp"];
        };
        BotList: {
            items: components["schemas"]["Bot"][];
        };
        QueueEntry: {
            match: components["schemas"]["MatchSummary"];
            /** @description 1 for the next match to start; 0 for running matches. */
            position: number;
            /** @description When the match should start; for running matches when it started. */
            estimated_start: components["schemas"]["Timestamp"];
            estimated_end: components["schemas"]["Timestamp"];
        };
        Queue: {
            /** @description No new matches start while the queue is paused. */
            paused: boolean;
            running: components["schemas"]["QueueEntry"][];
            /** @description In start order; at most 200 entries. */
            waiting: components["schemas"]["QueueEntry"][];
            waiting_total: number;
        };
        /**
         * @description PGN result; * if the game was aborted without rating.
         * @enum {unknown}
         */
        result: "1-0" | "0-1" | "1/2-1/2" | "*";
        /**
         * @description Machine-readable reason, the same codes as stored in the database.
         * @enum {unknown}
         */
        termination: "checkmate" | "resignation" | "timeout" | "illegal_move" | "protocol_violation" | "crash" | "memory_limit" | "startup_timeout" | "stalemate" | "threefold_repetition" | "fifty_move_rule" | "insufficient_material" | "timeout_insufficient_material" | "max_moves" | "aborted";
        /** @description Move in UCI notation, promotion piece in lower case. The null move 0000 is not allowed. */
        uci: string;
        /** @description Optional search information, shown publicly in the viewer (E33). Display only. */
        info: {
            depth?: number;
            seldepth?: number;
            /** @description Score in centipawns from the bot's point of view. */
            score_cp?: number;
            /** @description Mate in this many moves; negative if the bot gets mated. */
            score_mate?: number;
            nodes?: number;
            /** @description Principal variation, starting with the move played. */
            pv?: components["schemas"]["uci"][];
            text?: string;
        };
    };
    responses: {
        /** @description A parameter is invalid (code invalid_parameter). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such resource (code not_found). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The database is unreachable (code unavailable). */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        MatchId: components["schemas"]["Id"];
        /** @description Page size. */
        Limit: number;
        /** @description Number of items to skip. */
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API answers and reaches the database. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    list_matches: {
        parameters: {
            query?: {
                /** @description Only matches with this status. */
                status?: components["schemas"]["MatchStatus"];
                /** @description Only matches in which this bot plays either colour. */
                bot_id?: components["schemas"]["Id"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
                /** @description Number of items to skip. */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of matches. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchPage"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    get_match: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The match. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    get_match_pgn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One PGN game. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-chess-pgn": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    list_bots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The bots. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotList"];
                };
            };
        };
    };
    get_bot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bot_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The bot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bot"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    get_queue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The queue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Queue"];
                };
            };
        };
    };
}
