import type { components } from "./schema";

type Schemas = components["schemas"];

export type ApiToken = Schemas["ApiToken"];
export type CreatedApiToken = Schemas["CreatedApiToken"];

export type Bot = Schemas["Bot"];
export type BotDetail = Schemas["BotDetail"];
export type BotDetails = Schemas["BotDetails"];
export type BotFile = Schemas["BotFile"];
export type BotStatus = Schemas["BotStatus"];
export type BotUpdate = Schemas["BotUpdate"];
export type CreatedInvite = Schemas["CreatedInvite"];
export type CurrentUser = Schemas["CurrentUser"];
export type Discipline = Schemas["Discipline"];
export type DisciplineRequest = Schemas["DisciplineRequest"];
export type DisciplineUpdate = Schemas["DisciplineUpdate"];
export type EnqueueRequest = Schemas["EnqueueRequest"];
export type Finding = Schemas["Finding"];
export type ErrorCode = Schemas["Error"]["code"];
export type Invite = Schemas["Invite"];
export type Match = Schemas["Match"];
export type MatchPage = Schemas["MatchPage"];
export type MatchStatus = Schemas["MatchStatus"];
export type MatchSummary = Schemas["MatchSummary"];
export type Move = Schemas["Move"];
export type MoveInfo = NonNullable<Move["info"]>;
export type OneTimeLink = Schemas["OneTimeLink"];
export type OwnBotUpdate = Schemas["OwnBotUpdate"];
export type OwnMatchRequest = Schemas["OwnMatchRequest"];
export type PlayRequest = Schemas["PlayRequest"];
export type PlaySeat = Schemas["PlaySeat"];
export type PlaySettings = Schemas["PlaySettings"];
export type Queue = Schemas["Queue"];
export type QueueEntry = Schemas["QueueEntry"];
export type Rating = Schemas["Rating"];
export type RatingChange = Schemas["RatingChange"];
export type Role = Schemas["Role"];
export type SessionState = Schemas["SessionState"];
export type Side = Schemas["Side"];
export type StoredDiscipline = Schemas["StoredDiscipline"];
export type Termination = Schemas["termination"];
export type TestGame = Schemas["TestGame"];
export type User = Schemas["User"];
export type UserUpdate = Schemas["UserUpdate"];
export type VerificationReport = Schemas["VerificationReport"];
export type VerificationStage = Schemas["VerificationStage"];
