"""Collection names (datenmodell.md)."""

BOTS = "bots"
MATCHES = "matches"
JOBS = "jobs"
SETTINGS = "settings"
MIGRATIONS = "schema_migrations"
USERS = "users"
SESSIONS = "sessions"
INVITES = "invites"
PASSWORD_RESETS = "password_resets"
AUDIT_LOG = "audit_log"
RATE_LIMITS = "rate_limits"
VERIFICATION_REPORTS = "verification_reports"
DISCIPLINES = "disciplines"
# GridFS bucket for the uploaded files of bots (E82): bot_files.files and bot_files.chunks.
BOT_FILES = "bot_files"
