"""Collection names (datenmodell.md)."""

BOTS = "bots"
MATCHES = "matches"
JOBS = "jobs"
SETTINGS = "settings"
MIGRATIONS = "schema_migrations"
USERS = "users"
SESSIONS = "sessions"
INVITES = "invites"
PASSWORD_RESETS = "password_resets"
AUDIT_LOG = "audit_log"
RATE_LIMITS = "rate_limits"
